### ISSUE TITLE
Checkpoint sequential segments should equal number of layers instead of 1?

### ISSUE THREAD

**Issue by aced125** [lucidrains/En-transformer#4]
https://github.com/lucidrains/En-transformer/blob/a37e635d93a322cafdaaf829397c601350b23e5b/en_transformer/en_transformer.py#L527

Looking at the source code here: https://pytorch.org/docs/stable/_modules/torch/utils/checkpoint.html#checkpoint_sequential

**Comment by lucidrains** [comment]
oh yes, i think you are right - let me know if 0.5.1 fixes things

**Comment by lucidrains** [comment]
@aced125 are you still finding En-transformer to be better suited for your problem than IPA?
